name: linux
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name : checkout
        uses : actions/checkout@v2.3.1
      - name : add permission and run commands
        run : chmod +x commands.sh ; ./commands.sh
      - name : publish build
        uses : actions/upload-artifact@v2
        with :
          name : friccbot_cpp
          path : cpp/
      - name : publish build
        uses : actions/upload-artifact@v2
        with :
          name : friccbot_js
          path : bot.js
      - name : publish build
        uses : actions/upload-artifact@v2
        with :
          name : friccbot_neko
          path : bot.n
      - name : publish build
        uses : actions/upload-artifact@v2
        with :
          name : friccbot_csharp
          path : csharp/bin/