name: windows 
on: [push]
jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - name : setup haxelib
        run : haxe_bin/haxelib setup
      - name : install haxicord
        run : haxelib git https://github.com/RaidAndFade/Haxicord.git
      - name : install hxcpp
        run : haxelib install hxcpp

      - uses : actions/checkout@v2.3.1

      - name : build haxe code and cpp
        run : haxe compile.hxml
      - name : publish build
        uses : actions/upload-artifact@v2
        with :
          name : friccbot
          path : bin/