name: windows 
on: [push]
jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - name : checkout
        uses : actions/checkout@v2.3.1
      - name : install scoop, haxe and neko and do commands
        run : |
          Set-ExecutionPolicy RemoteSigned -scope CurrentUser
          iwr -useb get.scoop.sh | iex
          refreshenv
          scoop install haxe
          haxelib setup ../
          haxelib install hxcpp
          haxelib install hxcs
          haxelib git haxicord https://github.com/RaidAndFade/Haxicord.git
          haxe cpp.hxml
          haxe js.hxml
          haxe csharp.hxml
          haxe neko.hxml
      - name : publish build
        uses : actions/upload-artifact@v2
        with :
          name : friccbot_cpp
          path : cpp/
      - name : publish build
        uses : actions/upload-artifact@v2
        with :
          name : friccbot_js
          path : bot.js
      - name : publish build
        uses : actions/upload-artifact@v2
        with :
          name : friccbot_neko
          path : bot.n
      - name : publish build
        uses : actions/upload-artifact@v2
        with :
          name : friccbot_csharp
          path : csharp/bin/