name: windows 
on: [push]
jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - name : checkout
        uses : actions/checkout@v2.3.1
      - name : runs commands
        run : ./commands.bat
      - name : publish build
        uses : actions/upload-artifact@v2
        with :
          name : friccbot
          path : bin/