name: windows 
on: [push]
jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - name : checkout
        uses : actions/checkout@v2.3.1
      - name : setup haxelib
        run : .\haxe_bin\haxelib setup
      - name : install haxicord
        run : .\haxe_bin\haxelib git https://github.com/RaidAndFade/Haxicord.git
      - name : install hxcpp
        run : .\haxe_bin\haxelib install hxcpp
      - name : build haxe code and cpp
        run : .\haxe_bin\haxe compile.hxml
      - name : publish build
        uses : actions/upload-artifact@v2
        with :
          name : friccbot
          path : bin/